### ISSUE TITLE
Connect-couchdb attempting to use document with leading underscore?

### ISSUE THREAD

**Issue by codehero** [tdebarochez/connect-couchdb#24]
Saw this in my error output when running docpad

Error: Only reserved document ids may start with underscore.
    at Request._callback (/home/docpad/node_modules/connect-couchdb/node_modules/yacw/lib/couch.js:31:15)
    at Request.self.callback (/home/docpad/node_modules/connect-couchdb/node_modules/request/index.js:142:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/home/docpad/node_modules/connect-couchdb/node_modules/request/index.js:856:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/home/docpad/node_modules/connect-couchdb/node_modules/request/index.js:808:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:883:14
    at process._tickCallback (node.js:415:13)

**Comment by codehero** [comment]
some lines from my couchdb log

[Tue, 09 Apr 2013 14:01:52 GMT] [info] [<0.30405.596>] 127.0.0.1 - - GET /analog10-connect/_0GaJ1yjmhcZI10kEGUaAtCb 404
[Tue, 09 Apr 2013 14:01:52 GMT] [info] [<0.30406.596>] 127.0.0.1 - - PUT /analog10-connect/_0GaJ1yjmhcZI10kEGUaAtCb 400
[Tue, 09 Apr 2013 14:01:52 GMT] [info] [<0.29961.596>] 127.0.0.1 - - GET /analog10-connect/_0GaJ1yjmhcZI10kEGUaAtCb 404

so it seems underscore is being used for a session document name

**Comment by tdebarochez** [comment]
Hi,

Thanks for your report.
Could you provide a test case, plz ?

Regards,

**Comment by codehero** [comment]
I'm not really sure how to provide a test case. How are those session documents ids generated?

**Comment by codehero** [comment]
OK I inspected the connect library itself and found the following function:

/**
- Return a unique identifier with the given `len`.
  *
-     utils.uid(10);
-     // => "FDaS435D2z"
  *
- @param {Number} len
- @return {String}
- @api private
  */

exports.uid = function(len) {
  return crypto.randomBytes(Math.ceil(len \* 3 / 4))
    .toString('base64')
    .slice(0, len)
    .replace(/\//g, '-')
    .replace(/+/g, '_');
};

So what is happening is that connect itself is generating session IDs with leading underscores...not good but we cannot change it.

So I propose modifying the _uri_encode function to work around leading underscores.

**Comment by tdebarochez** [comment]
It's difficult because we have to deal with a document id different to session id. I'm fixing that asap.
