### ISSUE TITLE
CouchDB auth doesn't work?

### ISSUE THREAD

**Issue by diversario** [tdebarochez/connect-couchdb#4]
```
var express = require('express'),
   app = express.createServer(),
    ConnectCouchDB = require('connect-couchdb')(express),
    store =  new ConnectCouchDB({name: 'user_sessions', username: 'user', password: 'pass', host: '123.45.67.8'});

app.use(express.session({ store : store, secret : 'secret!'}));
```

produces

```
connect-couchdb error:
{ stack: [Getter/Setter],
  arguments: undefined,
  type: undefined,
  message: 'Authentication required.',
  error: 'unauthorized',
  reason: 'Authentication required.',
  statusCode: 401 }
Error
    at _check_error (/node/node_modules/connect-couchdb/lib/connect-couchdb.js:29:25)
    at ConnectCouchDB.<anonymous> (/node/node_modules/connect-couchdb/lib/connect-couchdb.js:64:17)
    at native
    at [object Object].callback (/node/node_modules/connect-couchdb/lib/couch.js:31:21)
    at [object Object].<anonymous> (/node/node_modules/connect-couchdb/node_modules/request/main.js:290:21)
    at [object Object].emit (events.js:64:17)
    at IncomingMessage.<anonymous> (/node/node_modules/connect-couchdb/node_modules/request/main.js:278:54)
    at IncomingMessage.emit (events.js:81:20)
    at HTTPParser.onMessageComplete (http.js:133:23)
    at Socket.ondata (http.js:1228:22)
```

Username and password are tested to be correct. Am I doing something wrong here?

**Comment by diversario** [comment]
Apparently, the version from npm doesn't have code for username/password. Package.json says 0.2.0. Is there a revision of 0.2.0 that wasn't pushed into npm or something?

**Comment by tdebarochez** [comment]
You're right : that wasn't push to npm. Fairwinds is going to fixed it : after that I will push it to npm.
