### ISSUE TITLE
Not compatible with Node 0.6.0 or NPM 1.0.105

### ISSUE THREAD

**Issue by diversario** [tdebarochez/connect-couchdb#9]
NPM install log:

``` bash
npm ERR! error installing connect-couchdb@0.2.1 Error: No compatible version found: connect@'>=1.5.0- <1.6.0-'
npm ERR! error installing connect-couchdb@0.2.1 Valid install targets:
npm ERR! error installing connect-couchdb@0.2.1 ["0.0.1","0.0.2","0.0.3","0.0.4","0.0.5","0.0.6","0.1.0","0.2.0","0.2.1","0.2.2","0.2.3","0.2.4","0.2.5","0.2.6","0.2.7","0.3.0","0.4.0","0.5.0","0.5.1","0.5.2","0.5.3","0.5.4","0.5.5","0.5.6","0.5.7","0.5.8","0.5.9","0.5.10","1.0.0","1.0.1","1.7.2"]
npm ERR! error installing connect-couchdb@0.2.1     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:424:10)
npm ERR! error installing connect-couchdb@0.2.1     at /usr/local/lib/node_modules/npm/lib/cache.js:406:17
npm ERR! error installing connect-couchdb@0.2.1     at saved (/usr/local/lib/node_modules/npm/lib/utils/npm-registry-client/get.js:136:7)
npm ERR! error installing connect-couchdb@0.2.1     at Object.cb [as oncomplete] (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:36:9)
npm ERR! Error: No compatible version found: connect@'>=1.5.0- <1.6.0-'
npm ERR! Valid install targets:
npm ERR! ["0.0.1","0.0.2","0.0.3","0.0.4","0.0.5","0.0.6","0.1.0","0.2.0","0.2.1","0.2.2","0.2.3","0.2.4","0.2.5","0.2.6","0.2.7","0.3.0","0.4.0","0.5.0","0.5.1","0.5.2","0.5.3","0.5.4","0.5.5","0.5.6","0.5.7","0.5.8","0.5.9","0.5.10","1.0.0","1.0.1","1.7.2"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:424:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:406:17
npm ERR!     at saved (/usr/local/lib/node_modules/npm/lib/utils/npm-registry-client/get.js:136:7)
npm ERR!     at Object.cb [as oncomplete] (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:36:9)
npm ERR! Report this *entire* log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR! 
npm ERR! System Linux 2.6.38-12-generic
npm ERR! command "node" "/usr/local/bin/npm" "install" "api-easy" "async" "bcrypt" "cluster" "cluster.exception" "cradle" "connect" "connect-couchdb" "connect-form" "email" "express" "eyes" "formidable" "imagemagick" "jade" "JSV" "log" "mime" "qs" "rbytes" "request" "validator" "vows" "underscore"
npm ERR! cwd /home/diversario/Documents/Projects/stuff/node
npm ERR! node -v v0.6.0
npm ERR! npm -v 1.0.105

```

**Comment by tdebarochez** [comment]
fix in v0.2.2
